{% set name = "vak" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vak-{{ version }}.tar.gz
  sha256: 84f9c00c1da54e94669b88e699f0f1d2a549d5cc65e43a070e9a40757f73776f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - vak=vak.__main__:main

requirements:
  host:
    - pip
    - python >=3.8
    - flit-core
  run:
    - attrs >=19.3.0
    - crowsetta >=3.4.0,<4.0.0
    - dask-core >=2.10.1
    - evfuncs >=0.3.4
    - joblib >=0.14.1
    - matplotlib-base >=3.3.3
    - numpy >=1.18.1
    - pandas >=1.0.1
    - python >=3.8
    - scipy >=1.4.1
    - pysoundfile >=0.10.3
    - tensorboard >=2.8.0
    - toml >=0.10.2
    - pytorch >=1.7.1
    - torchvision >=0.5.0
    - tqdm >=4.42.1

test:
  imports:
    - vak
  commands:
    - pip check
    - vak --help
  requires:
    - pip

about:
  home: https://pypi.org/project/vak/
  summary: a neural network toolbox for animal vocalizations and bioacoustics
  dev_url: https://github.com/vocalpy/vak
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NickleDave
