{% set name = "vak" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vak-{{ version }}.tar.gz
  sha256: 75c74f8c771422f73c975a416b3f82a291b50398861f68beb04ddcb6b6a9177f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - vak=vak.__main__:main

requirements:
  host:
    - pip
    - python >=3.10
    - flit-core
  run:
    - attrs >=23.1.0
    - crowsetta >=5.0.3
    - dask >=2024.5.0
    - evfuncs >=0.3.4
    - joblib >=1.4.2
    - lightning >=2.2.4
    - matplotlib-base >=3.7.1
    - numpy >=1.24.0, <2.0
    - pandas >=1.4.0
    - pynndescent >=0.5.12
    - python >=3.10
    - scipy >=1.9.1
    - pysoundfile >=0.12.1
    - tensorboard >=2.8.0
    - tomlkit >=0.12.4
    - pytorch >=2.3.0
    - torchvision >=0.18.0
    - tqdm >=4.66.4
    - umap-learn >=0.5.6

test:
  imports:
    - vak
  commands:
    - pip check
    - vak --help
  requires:
    - pip

about:
  home: https://pypi.org/project/vak/
  summary: a neural network toolbox for animal vocalizations and bioacoustics
  dev_url: https://github.com/vocalpy/vak
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NickleDave
